spring.application.name=consumer-service
# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#(nested properties)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.consumer.model.OrderEvent

# Custom Topic Properties
topic.name=gi-topic2
#topic.dlq=gi-topic1-dlq

server.port=8082
